### PR TITLE
Dependencies and Quickstart

### PR DESCRIPTION
**Pull request by joshmccall221**
Know your mantra: ShuHaRi
============

git clone
npm i
npm test
npm serve 
vim

[Source: Martin Fowler-ShuHaRi](https://martinfowler.com/bliki/ShuHaRi.html)

### CODE REVIEW

**Comment by riojack** [comment]
*dependencies

We're you getting errors about `babel-register` being absent?

**Comment by joshmccall221** [comment]
Yep yep yep: 

```
npm run build          

> github@0.0.11 build /Users/ubu/Repos/photography
> npm test && npm run webpack


> github@0.0.11 test /Users/ubu/Repos/photography
> mocha test --recursive

module.js:339
    throw err;
    ^

Error: Cannot find module 'babel-register'
```

**Comment by joshmccall221** [comment]
Prolly doesn't hurt anything but....

npm run webpack

```
> github@0.0.11 webpack /Users/ubu/Repos/photography
> webpack

Hash: 52488035510269597e4d
Version: webpack 1.14.0
Time: 5682ms
             Asset     Size  Chunks             Chunk Names
    application.js  41.5 kB    0, 1  [emitted]  application
application.min.js  17.8 kB    1, 0  [emitted]  application.min
    + 19 hidden modules

ERROR in ./index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./sheets in /Users/ubu/Repos/photography
 @ ./index.js 10:15-34
```

**Comment by riojack** [comment]
Ah, yes, the `./sheets` thing.  I need to fix that.  That is only on my machine at home.

**Comment by riojack** [comment]
btw, what version of node are you using?  I believe at home I am using 6.x.

**Comment by joshmccall221** [comment]
ha... thats why I included in the package.json:
```
  "bootstrap:dev_setup":". $NVM_DIR/nvm.sh && nvm install 4.2.0; nvm use 4.2.0",

```
I will update it

**Comment by joshmccall221** [comment]
node v6.9.5

**Pull request merged**
